<table width="50%" border="0" cellspacing="5" cellpadding="0" align="center" style="width: 560px; padding: 15px;">
	<tr height="10">
		<td></td>
	</tr>
	<tr>
		<td colspan="2">
			<h1 style="margin-bottom: 0;">New Website Lead</h1>
			<div style="padding-top: 0px;margin-top: 0px;font-size: 21px;">Website Registration</div>
		</td>
	</tr>
	<tr>
		<td style="padding-bottom: 20px;"><strong>---------------------------------------------------------------------</strong></td>
	</tr>
	<tr>
		<td align="left" valign="top" style="padding:5px;"><strong>Name: </strong>{$user_name|replace:'_':' '|lower|ucwords}</td>
{*		<td>{str_replace('_',' ',$user_name)}</td>*}
	</tr>
	<tr>
		<td align="left" valign="top" style="padding:5px;"><strong>Email: </strong>{$user_email}</td>
	</tr>

	<tr>
		<td align="left" valign="top" style="padding:5px;"><strong>Phone(used as a password): </strong>{$user_pass}</td>
	</tr>

	<tr>
		<td align="left" valign="top" style="padding:5px;"><strong>Lead Date: </strong>{$LeadDate}</td>
	</tr>

{*	<tr>
		<td align="left" valign="top" style="padding:5px;padding-top: 25px;">
			<strong>View Lead Profile:</strong>
			<p style="margin: 0;"><a href="{$LeadProfile}" target="_blank">{$LeadProfile}</a></p>
		</td>
	</tr>*}

	{*<tr>
		<td align="left" valign="top" style="padding:5px;padding-top: 25px;">
			<strong>Registration Page:</strong>
			<p style="margin: 0;"><a href="{$RegistrationPage}" target="_blank">{$RegistrationPage}</a></p>
		</td>
	</tr>*}

	<tr>
		<td align="left" valign="top" style="padding:5px;padding-top: 25px;">
			<strong>Source: </strong><a href="{$RegistrationPage}" target="_blank">{$RegistrationPage}</a>
		</td>
	</tr>

	<tr>
		<td style="padding-top: 20px;"><strong>---------------------------------------------------------------------</strong></td>
	</tr>
	<tr>
		<td><p style="margin-top: 0px;">DO NOT REPLY TO THIS EMAIL. This email was auto-generated by your website.</p></td>
	</tr>

</table>
