<table align="center" width="50%" border="0" cellspacing="5" cellpadding="0" style="margin-top: 10px;width: 560px; padding: 15px;">
    <tr height="10">
        <td></td>
    </tr>
    {* <tr>
         <td colspan="2" style="color:#000; text-align:left; font-size:1em; font-weight:700">Dear <font color="#094B6B">Sir/Madam</font></td>
     </tr>
     <tr>
         <td colspan="2"><strong>Schedule Showing request has been received for MLS Number# {$Record.MLS_NUM}.</strong></td>
     </tr>*}
    <tr>
        <td colspan="2">
            <h1 style="margin-bottom: 0;">Property Inquiry</h1>
            <div style="padding-top: 0px;margin-top: 0px;font-size: 21px;">Details of the Inquiry</div>
        </td>
    </tr>
    <tr>
        <td style="padding-bottom: 20px;"><strong>---------------------------------------------------------------------</strong></td>
    </tr>
    {* <tr>
         <td colspan="2"><font color="#094B6B">User Details :</font></td>
     </tr>*}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Name................</strong> {$frmData.lead_first_name|lower|ucwords} {$frmData.lead_last_name|lower|ucwords}</td>
    </tr>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Email................</strong> {$frmData.lead_email}</td>
    </tr>
    {if $frmData.lead_home_phone != ''}
        <tr>
            <td align="left" valign="top" style="padding:5px;"><strong>Phone................</strong> {$frmData.lead_home_phone}</td>
        </tr>
    {/if}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Price................</strong> {$site_currency}{$Record.ListPrice|number_format:0}</td>
    </tr>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Listing Address................</strong> {$Record.address_short}</td>
    </tr>
    {if isset($Record.CityName) && $Record.CityName != ''}
        <tr>
            <td align="left" valign="top" style="padding:5px;"><strong>City................</strong> {$Record.CityName}</td>
        </tr>
    {/if}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Listing MLS................</strong> {$Record.MLS_NUM}</td>
    </tr>

    {if isset($Record.PropertyType) && $Record.PropertyType != ''}
        <tr>
            <td align="left" valign="top" style="padding:5px;"><strong>Type................</strong> {$Record.PropertyType}</td>
        </tr>
    {/if}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Lead Date................ </strong>{$LeadDate}</td>
    </tr>

    <tr>
        <td align="left" valign="top" style="padding:5px;padding-top: 25px;">
            <strong>Comments:</strong>
            <p style="margin: 0;">{$frmData.lead_comment|nl2br}</p>
        </td>
    </tr>


    {*<tr>
        <td colspan="2" style="padding-top: 25px;padding-bottom: 25px;">
            <h1>Lead Profile</h1>
        </td>
    </tr>
    {if isset($Record.CityName) && $Record.CityName != ''}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Top City................</strong> {$Record.CityName}</td>
    </tr>
    {/if}

    {if isset($Record.PropertyType) && $Record.PropertyType != ''}
	<tr>
		<td align="left" valign="top" style="padding:5px;"><strong>Property Type................</strong> {$Record.PropertyType}</td>
	</tr>
    {/if}
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Price Point................</strong> {$site_currency}{$Record.ListPrice|number_format:0}</td>
    </tr>

    <tr>
        <td align="left" valign="top" style="padding:5px;padding-top: 25px;">
            <strong>View Lead Profile:</strong>
            <p style="margin: 0;"><a href="{$LeadProfile}" target="_blank">{$LeadProfile}</a></p>
        </td>
    </tr>*}

    <tr>
        <td style="padding-top: 20px;"><strong>---------------------------------------------------------------------</strong></td>
    </tr>
    <tr>
        <td><p style="margin-top: 0px;">DO NOT REPLY TO THIS EMAIL. This email was auto-generated by your website.</p></td>
    </tr>
    {*<tr>
        <td align="right" valign="top" style="padding:5px; background-color:#eaeaea"><strong>Listing Agent :</strong></td>
        <td>{$Record.Agent_FullName|lower|ucwords}</td>
    </tr>*}

</table>