<?php
#=============================================================================================================================
#	File Name		:	IDXData.php
#=============================================================================================================================
# Include class
require_once(dirname(__FILE__) . '/CustomClass.php');

class IDXListingData extends CustomClass
{
	#=========================================================================================================================
	#	Function Name	:   IDXData
	#	Purpose			:	Simple constructor
	#	Return			:	None
	#-------------------------------------------------------------------------------------------------------------------------
    function IDXListingData($isPopulateSchema)
    {
		global $physical_path, $virtual_path, $config;

		//RETS Master Detail
		/*include_once($physical_path['DB_Access']. '/MLSMaster.php');
		$this->objMLSMaster = new MLSMaster();

		$this->picPath['InActive_MLS_ID']		= $this->objMLSMaster->getInActiveMLS();*/

		//print $this->picPath['InActive_MLS_ID'];die;
		$this->picPath['MLS_Pic_Folder']		= array(
														"0"	=>	"other",
														"1"	=>	"creamls",
                                                        "2" =>  "cslisting",
													);

		# Table name
		$this->Data['Agent_Table']				=	$config['Table_Prefix']. 'listing_agent';
		$this->Data['Office_Table']				=	$config['Table_Prefix']. 'listing_office';
		$this->Data['Metadata_Table']			=	$config['Table_Prefix']. 'listing_metadata';

		$this->Data['TableName']				=	$config['Table_Prefix']. 'listing_master';
		$this->Data['Listing_Address']			=	$config['Table_Prefix']. 'listing_address';
		$this->Data['Listing_Additional_Info']	=	$config['Table_Prefix']. 'listing_additional_info';
		$this->Data['Statistic_Table']			=	$config['Table_Prefix']. 'listing_statistic';
		$this->Data['MLS_Open_House_Table'] 	= 	$config['Table_Prefix']. 'listing_open_house';
		$this->Data['MLS_Photo_Table'] 			= 	$config['Table_Prefix']. 'listing_photos';
		$this->Data['MLS_Virtual_Tour_Table'] 	= 	$config['Table_Prefix']. 'listing_virtual_tours';
		$this->Data['Listing_Price_Log']		=	$config['Table_Prefix']. 'listing_price_log';
		$this->Data['Listing_Deleted']          =   $config['Table_Prefix']. 'listing_deleted';
		$this->Data['Listing_Room_Info']		=	$config['Table_Prefix']. 'listing_room_info';
        $this->Data['UserFavoriteProperty']		=	$config['Table_Prefix']. 'user_favorite_property';

		$this->Data['MLS_Master']				=	$config['Table_Prefix']. 'mls_master';
        $this->Data['Listing_Unit_Info']		=	$config['Table_Prefix']. 'listing_unit_info';

		$this->Data['PriceWatch_Table']			=	$config['Table_Prefix']. 'listing_price_watch_list';

		$this->Data['GeoState']					=	$config['Table_Prefix']. 'geo_state';
		$this->Data['Onboard_County_Place']	    =	$config['Table_Prefix']. 'onboard_api_county_place';

		# Field Information
		$this->Data['F_OfficeHeader']			=
			array(
					'Office_Name'				=>	array(	TITLE	=>	'Office Name',
															WIDTH	=>	'35%',
														),
					'Office_City'				=>	array(	TITLE	=>	'City',
															WIDTH	=>	'18%',
														),
					'Office_State'				=>	array(	TITLE	=>	'State',
															WIDTH	=>	'10%',
														),
					'Office_Zip'				=>	array(	TITLE	=>	'Zip Code',
															WIDTH	=>	'10%',
														),
					'Office_Phone'				=>	array(	TITLE	=>	'Phone',
															WIDTH	=>	'20%',
														),
				);

		# Field information
		$this->Data['F_OfficeFieldInfo']				=
			array(
					'OfficeInformation'			=>	array(	GROUP_TITLE		=>	'Office Information'),
					'Office_Name'				=>	array(	TITLE			=>	'Name :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Address1'			=>	array(	TITLE			=>	'Address 1 :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Address2'			=>	array(	TITLE			=>	'Address 2 :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_City'				=>	array(	TITLE			=>	'City :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_State'				=>	array(	TITLE			=>	'State :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Zip'				=>	array(	TITLE			=>	'Zip Code :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Phone'				=>	array(	TITLE			=>	'Phone :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Email'				=>	array(	TITLE			=>	'Email :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Web'				=>	array(	TITLE			=>	'Web :',
															CNT_TYPE		=>	C_TEXT,
														),
					'Office_Fax'				=>	array(	TITLE			=>	'Fax :',
															CNT_TYPE		=>	C_TEXT,
														),
				);

		$this->Pic_Path						=	$virtual_path['Assets_Url'].'/pictures/property/';

		# Include Module Data
		if($isPopulateSchema) $this->populateSchema();

		# Intialize parent class
		parent::__construct();
	}
	#=========================================================================================================================
	#	Function Name	:   ModuleData
	#-------------------------------------------------------------------------------------------------------------------------
	function populateSchema()
	{

		global $physical_path, $config;

		include_once($physical_path['DB_Access']. '/Metadata.php');
		$objMetadata = new Metadata();

		$arrMetadataValue = $objMetadata->getAllMetadataValue();
		$arrOfficeParam['ActiveOfficeFlag'] = true;

		# Field information
		$this->Data['F_FieldInfo']				=
			array(
					'GeneralInformation'		=>	array(	GROUP_TITLE		=>	'General'),
					'MainPicData'				=>	array(	TITLE			=>	'Main Picture',
															CNT_TYPE		=>	C_PICFILE,
															CNT_MAXLEN		=>	255,
															DESC			=>	"Valid Picture Format: ". $config['valid_pic_format'],
															CREATE_THUMB	=>	false,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_EXTENTION,
															VAL_EXT			=>	$config['valid_pic_format'],
														),
					'ListingID'					=>	array(	TITLE			=>	'Listing ID',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	20,
															CNT_MAXLEN		=>	20,
															TABLE_PK_ID		=>	true,
															CNT_READONLY	=>  true,
														),
					'Agent_ID'					=>	array(	TITLE			=>	'Agent',
															CNT_TYPE		=>	C_COMBOBOX,
															IS_NUMBER		=>  true,
															OPTION			=>	$this->getAgentKeyValueArray(),
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'OfficeID'					=>	array(	TITLE			=>	'Office',
															CNT_TYPE		=>	C_COMBOBOX,
															IS_NUMBER		=>  true,
															OPTION			=>	$this->getOfficeKeyValueArray($arrOfficeParam),
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'PropertyType'				=>	array(	TITLE			=>	'Property Type',
															CNT_TYPE		=>	C_TEXT,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_EMPTY,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	25,
														),
					'PropertyStyle'				=>	array(	TITLE			=>	'Property Style',
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															OPTION			=>	$arrMetadataValue['PropertyStyle'],
															CONV_STR		=>	true,
														),
					'SubType'					=>	array(	TITLE			=>	'Sub Type',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['SubType'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'ListType'					=>	array(	TITLE			=>	'List Type',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['ListType'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'RentalType'				=>	array(	TITLE			=>	'Rental Type',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['RentalType'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'BusinessType'				=>	array(	TITLE			=>	'Business Type',
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															OPTION			=>	$arrMetadataValue['BusinessType'],
															CONV_STR		=>	true,
														),
					'SubBusinessType'			=>	array(	TITLE			=>	'Sub Business Type',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
														),
					'BathsFull'					=>	array(	TITLE			=>	'Baths Full',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	15,
															CNT_MAXLEN		=>	3,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'BathsHalf'					=>	array(	TITLE			=>	'Baths Half',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	3,
															CNT_MAXLEN		=>	15,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'Beds'						=>	array(	TITLE			=>	'Beds',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	3,
															CNT_MAXLEN		=>	15,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'Acres'						=>	array(	TITLE			=>	'Acres',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	100,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_FLOAT,
														),
					'ListPrice'					=>	array(	TITLE			=>	'List Price',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	10,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'ListPriceOriginal'			=>	array(	TITLE			=>	'List Price Original',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	11,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'SQFT'					=>	array(	TITLE			=>	'SQFT Total',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	10,
															CNT_MAXLEN		=>	20,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_FLOAT,
														),
					'SQFTLand'					=>	array(	TITLE			=>	'SQFT Land',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	10,
															CNT_MAXLEN		=>	20,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_FLOAT,
														),
					'YearBuilt'					=>	array(	TITLE			=>	'Year Built',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	10,
															CNT_MAXLEN		=>	4,
														),
					'LocationInformation'		=>	array(	GROUP_TITLE		=>	'Location'),
					'StreetNumber'				=>	array(	TITLE			=>	'Street Number',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	20,
															CNT_MAXLEN		=>	8,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'StreetName'				=>	array(	TITLE			=>	'Street Name',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_EMPTY,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'StreetDirection'			=>	array(	TITLE			=>	'Street Direction',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['StreetDirection'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'ZipCode'					=>	array(	TITLE			=>	'Zip Code',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	20,
															CNT_MAXLEN		=>	10,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'CityName'					=>	array(	TITLE			=>	'City Name',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_EMPTY,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'State'						=>	array(	TITLE			=>	'State',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	20,
															CNT_MAXLEN		=>	2,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_EMPTY,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'Location'					=>	array(	TITLE			=>	'Location',
															OPTION			=>	$arrMetadataValue['Location'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
															CONV_STR		=>	true,
														),
					'Neighborhood'				=>	array(	TITLE			=>	'Neighborhood',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	255,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
														),
					'Latitude'					=>	array(	TITLE			=>	'Latitude',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>	true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	35,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_FLOAT,
														),
					'Longitude'					=>	array(	TITLE			=>	'Longitude',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>	true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	35,
															TABLE_NAME		=>  $this->Data['Sub_TableName'],
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_FLOAT,
														),
					'ListingFeatureInformation'	=>	array(	GROUP_TITLE		=>	'Listing Info.'),
					'UnitNo'					=>	array(	TITLE			=>	'Unit No',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	25,
														),
					'ListingDate'				=>	array(	TITLE			=>	'Listing Date',
															CNT_TYPE		=>	C_DATEPICKER,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	20,
														),
					'PhotoDate'					=>	array(	TITLE			=>	'Photo Date',
															CNT_TYPE		=>	C_DATEPICKER,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	20,
														),
					'Disclosures'				=>	array(	TITLE			=>	'Disclosures',
															OPTION			=>	$arrMetadataValue['Disclosures'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'Region'					=>	array(	TITLE			=>	'Region',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['Region'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'Parking'				=>	array(	TITLE			=>	'Number of Parking',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>	true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	11,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'Furnished'					=>	array(	TITLE			=>	'Furnished',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['Furnished'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'Roofing'					=>	array(	TITLE			=>	'Roofing',
															OPTION			=>	$arrMetadataValue['Roofing'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'RoadFrontage'				=>	array(	TITLE			=>	'Road Frontage',
															OPTION			=>	$arrMetadataValue['RoadFrontage'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'PropertyFrontage'			=>	array(	TITLE			=>	'Property Frontage',
															OPTION			=>	$arrMetadataValue['PropertyFrontage'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'ExpensesInclude'			=>	array(	TITLE			=>	'Expenses Include',
															OPTION			=>	$arrMetadataValue['ExpensesInclude'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'GarageArea'				=>	array(	TITLE			=>	'Garage Area',
															CNT_TYPE		=>	C_TEXT,
															IS_NUMBER		=>  true,
															CNT_SIZE		=>	30,
															CNT_MAXLEN		=>	10,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_INT,
														),
					'Zoning'					=>	array(	TITLE			=>	'Zoning',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['Zoning'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'Showing'					=>	array(	TITLE			=>	'Showing',
															OPTION			=>	$arrMetadataValue['Showing'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'Pool'						=>	array(	TITLE			=>	'Pool',
															OPTION			=>	$arrMetadataValue['Pool'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'FloorCovering'				=>	array(	TITLE			=>	'FloorCovering',
															OPTION			=>	$arrMetadataValue['FloorCovering'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'PetsYN'					=>	array(	TITLE			=>	'Pets?',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	array('Y' => 'Yes', 'N' => 'No'),
														),
					'Stories'					=>	array(	TITLE			=>	'Stories',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	255,
														),
					'Occupancy'					=>	array(	TITLE			=>	'Occupancy',
															OPTION			=>	$arrMetadataValue['Occupancy'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'DescriptionInformation'	=>	array(	GROUP_TITLE		=>	'Description'),
					'Amenities'					=>	array(	TITLE			=>	'Amenities',
															OPTION			=>	$arrMetadataValue['Amenities'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'Parking'					=>	array(	TITLE			=>	'Parking',
															OPTION			=>	$arrMetadataValue['Parking'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'Utilities'					=>	array(	TITLE			=>	'Utilities',
															OPTION			=>	$arrMetadataValue['Utilities'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'UnitFeatures'				=>	array(	TITLE			=>	'Unit Features',
															OPTION			=>	$arrMetadataValue['UnitFeatures'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'AdditionalRooms'			=>	array(	TITLE			=>	'Additional Rooms',
															OPTION			=>	$arrMetadataValue['AdditionalRooms'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'CommunityAssociation'		=>	array(	TITLE			=>	'Community Association',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	100,
														),
					'LotsDescription'			=>	array(	TITLE			=>	'Lots Description',
															OPTION			=>	$arrMetadataValue['LotsDescription'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'DivisionDesc'				=>	array(	TITLE			=>	'Division Description',
															CNT_TYPE		=>	C_COMBOBOX,
															OPTION			=>	$arrMetadataValue['DivisionDesc'],
															DEF_OPTION		=>	array('value' => '', 'text' => 'Select'),
														),
					'BuildingUse'				=>	array(	TITLE			=>	'Building Use',
															OPTION			=>	$arrMetadataValue['BuildingUse'],
															CNT_TYPE		=>	C_CHECKBOX,
															CNT_COL			=>  3,
															CONV_STR		=>	true,
														),
					'PublicRemarks'				=>	array(	TITLE			=>	'Public Remarks ',
															DESC			=>	'<font color="#FF0000">* * Maximum 255 characters</font>',
															CNT_TYPE		=>	C_TEXTAREA,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_LEN|V_MAX,
															VAL_MAX			=>	'255',
															VAL_MSG			=>	'Maximum 255 characters allowed!!',
														),

					'SellerRemarks'				=>	array(	TITLE			=>	'SellerRemarks ',
															DESC			=>	'<font color="#FF0000">* * Maximum 255 characters</font>',
															CNT_TYPE		=>	C_TEXTAREA,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_LEN|V_MAX,
															VAL_MAX			=>	'255',
															VAL_MSG			=>	'Maximum 255 characters allowed!!',
														),
					'ShowingRemarks'			=>	array(	TITLE			=>	'Showing Remarks ',
															DESC			=>	'<font color="#FF0000">* * Maximum 255 characters</font>',
															CNT_TYPE		=>	C_TEXTAREA,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_LEN|V_MAX,
															VAL_MAX			=>	'255',
															VAL_MSG			=>	'Maximum 255 characters allowed!!',
														),
					'listing_description'		=>	array(	TITLE			=>	'Description ',
															DESC			=>	'<font color="#FF0000">* * Maximum 255 characters</font>',
															CNT_TYPE		=>	C_TEXTAREA,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_LEN|V_MAX,
															VAL_MAX			=>	'255',
															VAL_MSG			=>	'Maximum 255 characters allowed!!',
														),
					'listing_extra_features'	=>	array(	TITLE			=>	'Extra Features ',
															DESC			=>	'<font color="#FF0000">* * Maximum 255 characters</font>',
															CNT_TYPE		=>	C_TEXTAREA,
															VALIDATE		=>	true,
															VAL_TYPE		=>	V_LEN|V_MAX,
															VAL_MAX			=>	'255',
															VAL_MSG			=>	'Maximum 255 characters allowed!!',
														),
					'SchoolInfo'				=>	array(	GROUP_TITLE		=>	'School'),
					'Elementary_School'			=>	array(	TITLE			=>	'Elementary School',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
														),
					'High_School'				=>	array(	TITLE			=>	'High School',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
														),
					'Middle_School'				=>	array(	TITLE			=>	'Middle School',
															CNT_TYPE		=>	C_TEXT,
															CNT_SIZE		=>	50,
															CNT_MAXLEN		=>	25,
														),
					'listing_user_auth_id'		=>	array(	CNT_TYPE		=>	C_HIDDEN,
														),
					'Show_Listing_Flag'			=>	array(	CNT_TYPE		=>	C_HIDDEN,
														),
				);

	}
}
?>