<?php
/* Smarty version 4.2.1, created on 2023-12-06 05:57:22
  from '/home/650569.cloudwaysapps.com/bubwqcebhd/public_html/wp-content/plugins/CustomWpPlugin/email_templates/email_schedule_showing.tpl' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '4.2.1',
  'unifunc' => 'content_657053921f8de0_00419912',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '87316807e16e9872322febe8b8b9cdfd87578b2d' => 
    array (
      0 => '/home/650569.cloudwaysapps.com/bubwqcebhd/public_html/wp-content/plugins/CustomWpPlugin/email_templates/email_schedule_showing.tpl',
      1 => 1672221278,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_657053921f8de0_00419912 (Smarty_Internal_Template $_smarty_tpl) {
$_smarty_tpl->_checkPlugins(array(0=>array('file'=>'/home/650569.cloudwaysapps.com/bubwqcebhd/public_html/wp-content/plugins/CustomWpPlugin/libs/Smarty4/plugins/modifier.number_format.php','function'=>'smarty_modifier_number_format',),));
?>
<table align="center" width="50%" border="0" cellspacing="5" cellpadding="0" style="margin-top: 10px;width: 560px; padding: 15px;">
    <tr height="10">
        <td></td>
    </tr>
       <tr>
        <td colspan="2">
            <h1 style="margin-bottom: 0;">Property Inquiry</h1>
            <div style="padding-top: 0px;margin-top: 0px;font-size: 21px;">Details of the Inquiry</div>
        </td>
    </tr>
    <tr>
        <td style="padding-bottom: 20px;"><strong>---------------------------------------------------------------------</strong></td>
    </tr>
       <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Name: </strong> <?php echo ucwords(mb_strtolower($_smarty_tpl->tpl_vars['frmData']->value['lead_first_name'], 'UTF-8'));?>
 <?php echo ucwords(mb_strtolower($_smarty_tpl->tpl_vars['frmData']->value['lead_last_name'], 'UTF-8'));?>
</td>
    </tr>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Email: </strong> <?php echo $_smarty_tpl->tpl_vars['frmData']->value['lead_email'];?>
</td>
    </tr>
    <?php if ($_smarty_tpl->tpl_vars['frmData']->value['lead_home_phone'] != '') {?>
        <tr>
            <td align="left" valign="top" style="padding:5px;"><strong>Phone: </strong> <?php echo $_smarty_tpl->tpl_vars['frmData']->value['lead_home_phone'];?>
</td>
        </tr>
    <?php }?>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Price: </strong> <?php echo $_smarty_tpl->tpl_vars['site_currency']->value;
echo smarty_modifier_number_format($_smarty_tpl->tpl_vars['Record']->value['ListPrice'],0);?>
</td>
    </tr>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Listing Address: </strong> <?php echo $_smarty_tpl->tpl_vars['Record']->value['address_short'];?>
</td>
    </tr>
    <?php if ((isset($_smarty_tpl->tpl_vars['Record']->value['CityName'])) && $_smarty_tpl->tpl_vars['Record']->value['CityName'] != '') {?>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>City: </strong> <?php echo $_smarty_tpl->tpl_vars['Record']->value['CityName'];?>
</td>
    </tr>
    <?php }?>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Listing MLS: </strong> <?php echo $_smarty_tpl->tpl_vars['Record']->value['MLS_NUM'];?>
</td>
    </tr>

    <?php if ((isset($_smarty_tpl->tpl_vars['Record']->value['PropertyType'])) && $_smarty_tpl->tpl_vars['Record']->value['PropertyType'] != '') {?>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Type: </strong> <?php echo $_smarty_tpl->tpl_vars['Record']->value['PropertyType'];?>
</td>
    </tr>
    <?php }?>
    <tr>
        <td align="left" valign="top" style="padding:5px;"><strong>Lead Date: </strong><?php echo $_smarty_tpl->tpl_vars['LeadDate']->value;?>
</td>
    </tr>

    <tr>
        <td align="left" valign="top" style="padding:5px;padding-top: 25px;">
            <strong>Comments: </strong>
            <p style="margin: 0;"><?php echo nl2br($_smarty_tpl->tpl_vars['frmData']->value['lead_comment']);?>
</p>
        </td>
    </tr>

    <tr>
        <td align="left" valign="top" style="padding:5px;padding-top: 25px;">
            <strong>Source: </strong><a href="<?php echo $_smarty_tpl->tpl_vars['Source']->value;?>
" target="_blank"><?php echo $_smarty_tpl->tpl_vars['Source']->value;?>
</a>
        </td>
    </tr>


    
    <tr>
        <td style="padding-top: 20px;"><strong>---------------------------------------------------------------------</strong></td>
    </tr>
    <tr>
        <td><p style="margin-top: 0px;">DO NOT REPLY TO THIS EMAIL. This email was auto-generated by your website.</p></td>
    </tr>
    
</table><?php }
}
